use_frameworks!

platform :ios, '14.0'
#platform :macOS, '11.0'

target 'BootpayUI_Example' do
  pod 'BootpayUI', :path => '../'

  target 'BootpayUI_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
  installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
             end
        end
 end
end
